name: flblog
description: "A cross-platform Hexo blog management application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  markdown: ^7.3.0
  flutter_markdown: ^0.7.5+1
  markdown_widget: ^2.3.2
  file_picker: ^8.3.0
  path_provider: ^2.1.5
  path: ^1.9.0
  shared_preferences: ^2.5.2
  yaml: ^3.1.3
  yaml_writer: ^2.0.0
  url_launcher: ^6.3.1
  flutter_highlight: ^0.7.0
  highlight: ^0.7.0
  font_awesome_flutter: 10.7.0
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

